# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c579a2e05c8e75affff5f870e5d80289720f7be6b7e935ace5ba0e4db50af69af46c86c79456f976710ccc5dd40a3e27e4208ff5e50f07d84916fe23f5f2eadb

test:
  secret_key_base: 819327ac4b2df86fd05d054162feb1c37bd8b7e4df63098166e7cdf7acc7de8924871593307f62cca41548a74e5d4176e208107f6654076c8b5b190972036911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
